AWSTemplateFormatVersion: 2010-09-09
Parameters:
  project:
    Type: String
    Description: Alphanumeric and underscore
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  cfnBucketName:
    Type: String
    Description: Bucket that store cfn modules
  vpcNetworkAddress:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.0.0/18
  availabilityZone1:
    Type: "AWS::EC2::AvailabilityZone::Name"
    Description: Availability zone
  availabilityZone2:
    Type: "AWS::EC2::AvailabilityZone::Name"
    Description: Availability zone
  publicSubnet01Address:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.0.0/22
  publicSubnet02Address:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.4.0/22
  privateSubnet01Address:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.8.0/21
  privateSubnet02Address:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.16.0/21
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - project
          - cfnBucketName
      - Label:
          default: Network Configuration
        Parameters:
          - vpcNetworkAddress
          - availabilityZone1
          - availabilityZone2
          - publicSubnet01Address
          - publicSubnet02Address
          - privateSubnet01Address
          - privateSubnet02Address
    ParameterLabels:
      project:
        default: "Project's name:"
      cfnBucketName:
        default: "Cloudformation bucket:"
      vpcNetworkAddress:
        default: "VPC network address (CIDR Block):"
      availabilityZone1:
        default: "First availability zone:"
      availabilityZone2:
        default: "Second availability zone:"
      publicSubnet01Address:
        default: "Public subnet address for first AZ:"
      publicSubnet02Address:
        default: "Public subnet address for second AZ:"
      privateSubnet01Address:
        default: "Private subnet address on first AZ:"
      privateSubnet02Address:
        default: "Private subnet address on second AZ:"
Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/commons/modules/networking.yml
      Parameters: 
        project: !Ref project
        vpcNetworkAddress: !Ref vpcNetworkAddress
        availabilityZone1: !Ref availabilityZone1
        availabilityZone2: !Ref availabilityZone2
        publicSubnet01Address: !Ref publicSubnet01Address
        publicSubnet02Address: !Ref publicSubnet02Address
        privateSubnet01Address: !Ref privateSubnet01Address
        privateSubnet02Address: !Ref privateSubnet02Address

  GitConnection:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/commons/modules/codestar.yml
      Parameters: 
        project: !Ref project

  PipelineBucket:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/commons/modules/s3.yml
      Parameters: 
        bucketName: !Sub ${project}-pipeline-artifacts-${AWS::Region}

  TokensSecret:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/commons/modules/secrets-manager.yml
      Parameters: 
        project: !Ref project
        name: tokens
        secretTemplate: |
          {
            "DOCKER_HUB_USER": "",
            "DOCKER_HUB_TOKEN": ""
          }

Outputs:
  vpcId:
    Description: VPC Id
    Value: !GetAtt Network.Outputs.vpcId
    Export:
      Name: !Sub "${project}-foundations-vpcId"
  az01:
    Description: Availability Zone 1
    Value: !GetAtt Network.Outputs.az01
    Export:
      Name: !Sub "${project}-foundations-az01"
  az02:
    Description: Availability Zone 2
    Value: !GetAtt Network.Outputs.az02
    Export:
      Name: !Sub "${project}-foundations-az02"
  azList:
    Description: AZ Comma Separated List
    Value: !GetAtt Network.Outputs.azList
    Export:
      Name: !Sub "${project}-foundations-azList"
  publicSubnet01Id:
    Description: Public subnet 1
    Value: !GetAtt Network.Outputs.publicSubnet01Id
    Export:
      Name: !Sub "${project}-foundations-publicSubnet01Id"
  publicSubnet02Id:
    Description: Public subnet 2
    Value: !GetAtt Network.Outputs.publicSubnet02Id
    Export:
      Name: !Sub "${project}-foundations-publicSubnet02Id"
  publicSubnetsIdList:
    Description: Public subnet Ids Comma Separated List
    Value: !GetAtt Network.Outputs.publicSubnetsIdList
    Export:
      Name: !Sub "${project}-foundations-publicSubnetsIdList"
  privateSubnet01Id:
    Description: Private app subnet 1
    Value: !GetAtt Network.Outputs.privateSubnet01Id
    Export:
      Name: !Sub "${project}-foundations-privateSubnet01Id"
  privateSubnet02Id:
    Description: Private app subnet 2
    Value: !GetAtt Network.Outputs.privateSubnet02Id
    Export:
      Name: !Sub "${project}-foundations-privateSubnet02Id"
  privateSubnetsIdList:
    Description: Private subnet Ids Comma Separated List
    Value: !GetAtt Network.Outputs.privateSubnetsIdList
    Export:
      Name: !Sub "${project}-foundations-privateSubnetsIdList"
  gitConnectionARN:
    Value: !GetAtt GitConnection.Outputs.gitConnectionARN
    Export:
      Name: !Sub "${project}-foundations-gitConnectionARN"
  pipelineBucketName:
    Value: !GetAtt PipelineBucket.Outputs.bucketName
    Export:
      Name: !Sub "${project}-foundations-pipelineBucketName"
  pipelineBucketDomainName:
    Value: !GetAtt PipelineBucket.Outputs.bucketDomainName
    Export:
      Name: !Sub "${project}-foundations-pipelineBucketDomainName"
  tokensSecretARN:
    Description: Secret ARN
    Value: !GetAtt TokensSecret.Outputs.secretARN
    Export:
      Name: !Sub "${project}-foundations-tokensSecretARN"
  tokensSecretName:
    Description: Secret Name
    Value: !GetAtt TokensSecret.Outputs.secretName
    Export:
      Name: !Sub "${project}-foundations-tokensSecretName"