Parameters:
  project:
    Type: String
    Description: Project's name
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  cfnBucketName:
    Type: String
    Description: Bucket that store cfn modules
  frontendRepository:
    Type: String
    Description: "E.g: owner/repo_name"
  repositoryBranch:
    Type: String
    Default: main
    Description: Branch to deploy
  frontendSubdomain:
    Type: String
    Description: "Subdomain for the frontend, E.g: www"
    Default: www
    MinLength: "1"
  automaticDeploy:
    Type: String
    Description: Deploy frontend automatically on branch changes
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  buildInstanceComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
      - BUILD_GENERAL1_2XLARGE
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - project
          - environment
      - Label:
          default: Deploy information
        Parameters:
          - frontendRepository
          - repositoryBranch
          - frontendSubdomain
          - buildInstanceComputeType
          - automaticDeploy
      - Label:
          default: Other information
        Parameters:
          - cfnBucketName
    ParameterLabels:
      project:
        default: "Project's name:"
      environment:
        default: "Project's environment:"
      cfnBucketName:
        default: "Cloudformation bucket:"
      frontendRepository:
        default: "Frontend repository:"
      repositoryBranch:
        default: "Repository branch:"
      frontendSubdomain:
        default: "Frontend subdomain:"
      automaticDeploy:
        default: "Automatic deploy?"
      buildInstanceComputeType:
        default: "Build instance Compute type:"
Resources:
  WebsiteBucket:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/s3.yml
      Parameters: 
        bucketName: !Sub ${project}-${environment}-frontend-${frontendSubdomain}-${AWS::Region}

  Distribution:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/cloudfront.yml
      Parameters: 
        bucketName: !GetAtt WebsiteBucket.Outputs.bucketName
        bucketDomainName: !GetAtt WebsiteBucket.Outputs.bucketDomainName
        domain:
          Fn::ImportValue:
            !Sub "${project}-${environment}-shared-hostedZoneName"
        subdomain: !Ref frontendSubdomain
        certificateARN:
          Fn::ImportValue:
            !Sub "${project}-${environment}-shared-certificateARN"
        hostedZoneId:
          Fn::ImportValue:
            !Sub "${project}-${environment}-shared-hostedZoneId"

  Pipeline:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/pipeline/main.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        subdomain: !Ref frontendSubdomain
        cfnBucketName: !Ref cfnBucketName
        frontendRepository: !Ref frontendRepository
        repositoryBranch: !Ref repositoryBranch
        artifactsBucketName:
          Fn::ImportValue:
            !Sub "${project}-commons-pipelineBucketName"
        deploymentBucket: !GetAtt WebsiteBucket.Outputs.bucketName
        gitConnectionArn:
          Fn::ImportValue:
            !Sub "${project}-commons-gitConnectionARN"
        automaticDeploy: !Ref automaticDeploy
        buildInstanceComputeType: !Ref buildInstanceComputeType

Outputs:
  websiteBucketName:
    Value: !GetAtt WebsiteBucket.Outputs.bucketName
    Export:
      Name: !Sub "${project}-${environment}-frontend-websiteBucketName"
  websiteBucketDomainName:
    Value: !GetAtt WebsiteBucket.Outputs.bucketDomainName
    Export:
      Name: !Sub "${project}-${environment}-frontend-websiteBucketDomainName"
  distributionId:
    Value: !GetAtt Distribution.Outputs.distributionId
    Export:
      Name: !Sub "${project}-${environment}-frontend-distributionId"
  distributionDomain:
    Value: !GetAtt Distribution.Outputs.distributionDomain
    Export:
      Name: !Sub "${project}-${environment}-frontend-distributionDomain"