Parameters:
  project:
    Type: String
    Description: Project's name
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  cfnBucketName:
    Type: String
    Description: Bucket that store cfn modules
  frontendRepository:
    Type: String
    Description: "E.g: owner/repo_name"
  repositoryBranch:
    Type: String
    Default: main
    Description: Branch to deploy
  frontendSubdomain:
    Type: String
    Description: "Subdomain for the frontend, E.g: www"
    Default: www
    MinLength: "1"
    MaxLength: "3"
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - project
          - environment
      - Label:
          default: Other information
        Parameters:
          - cfnBucketName
          - frontendRepository
          - repositoryBranch
          - frontendSubdomain
    ParameterLabels:
      project:
        default: "Project's name:"
      environment:
        default: "Project's environment:"
      cfnBucketName:
        default: "Cloudformation bucket:"
      frontendRepository:
        default: "Frontend repository:"
      repositoryBranch:
        default: "Repository branch:"
      frontendSubdomain:
        default: "Frontend subdomain:"
Resources:
  WebsiteBucket:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/s3.yml
      Parameters: 
        bucketName: !Sub ${project}-${environment}-frontend-${AWS::Region}

  Distribution:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/cloudfront.yml
      Parameters: 
        bucketName: !GetAtt WebsiteBucket.Outputs.bucketName
        bucketDomainName: !GetAtt WebsiteBucket.Outputs.bucketDomainName
        domain:
          Fn::ImportValue:
            !Sub "${project}-${environment}-commons-hostedZoneName"
        subdomain: !Ref frontendSubdomain
        certificateARN:
          Fn::ImportValue:
            !Sub "${project}-${environment}-commons-certificateARN"
        hostedZoneId:
          Fn::ImportValue:
            !Sub "${project}-${environment}-commons-hostedZoneId"

  Pipeline:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/pipeline/main.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        cfnBucketName: !Ref cfnBucketName
        frontendRepository: !Ref frontendRepository
        repositoryBranch: !Ref repositoryBranch
        deploymentBucket: !GetAtt WebsiteBucket.Outputs.bucketName

Outputs:
  websiteBucketName:
    Value: !GetAtt WebsiteBucket.Outputs.bucketName
    Export:
      Name: !Sub "${project}-${environment}-frontend-websiteBucketName"
  websiteBucketDomainName:
    Value: !GetAtt WebsiteBucket.Outputs.bucketDomainName
    Export:
      Name: !Sub "${project}-${environment}-frontend-websiteBucketDomainName"
  distributionId:
    Value: !GetAtt Distribution.Outputs.distributionId
    Export:
      Name: !Sub "${project}-${environment}-frontend-distributionId"
  distributionDomain:
    Value: !GetAtt Distribution.Outputs.distributionDomain
    Export:
      Name: !Sub "${project}-${environment}-frontend-distributionDomain"