Parameters:
  project:
    Type: String
    Description: Project's name
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  service:
    Type: String
  cfnBucketName:
    Type: String
    Description: Bucket that store cfn modules
  serviceRepository:
    Type: String
  repositoryBranch:
    Type: String
    Default: main
  deployService:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
Resources:
  Permissions:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/backend/service/modules/pipeline/iam.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        service: !Ref service
        artifactsBucketName: 
          Fn::ImportValue:
            !Sub "${project}-commons-pipelineBucketName"

  BuildProject:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/backend/service/modules/pipeline/codebuild.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        service: !Ref service
        codeBuildRoleArn: !GetAtt Permissions.Outputs.buildRoleArn
        
  PipelineProject:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/backend/service/modules/pipeline/codepipeline.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        service: !Ref service
        artifactsBucketName: 
          Fn::ImportValue:
            !Sub "${project}-commons-pipelineBucketName"
        repositoryName: !Ref serviceRepository
        repositoryBranch: !Ref repositoryBranch
        codePipelineRoleArn: !GetAtt Permissions.Outputs.pipelineRoleArn
        gitConnectionArn: 
          Fn::ImportValue:
            !Sub "${project}-commons-gitConnectionARN"
        buildProjectName: !GetAtt BuildProject.Outputs.codeBuildProjectName
        deployService: !Ref deployService