Parameters:
  project:
    Type: String
  environment:
    Type: String
  name:
    Type: String
  secretTemplate:
    Type: String
Resources:
  Secret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub 'secm-${project}-${environment}-${name}'
      Description: !Sub 'Secret ${name}'
      SecretString: !Ref secretTemplate
Outputs:
  secretARN:
    Description: Secret ARN
    Value: !Ref Secret
  secretName:
    Description: Secret Name
    Value: !Sub 'secm-${project}-${environment}-${name}'