AWSTemplateFormatVersion: 2010-09-09
Parameters:
  project:
    Type: String
    Description: Alphanumeric and underscore
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  environment:
    Type: String
    Description: Select one environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  cfnBucketName:
    Type: String
    Description: Bucket that store cfn modules
  parentHostedZoneId:
    Type: String
    Description: This hosted zone must have been previously created
  parentHostedZoneName:
    Type: String
    Description: This hosted zone must have been previously created
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - project
          - environment
      - Label:
          default: Other information
        Parameters:
          - cfnBucketName
          - parentHostedZoneId
          - parentHostedZoneName
    ParameterLabels:
      project:
        default: "Project's name:"
      environment:
        default: "Project's environment:"
      cfnBucketName:
        default: "Cloudformation bucket:"
      parentHostedZoneId:
        default: "Parent Hosted Zone Id:"
      parentHostedZoneName:
        default: "Parent Hosted Zone Name:"
Conditions:
  isNonProd: !Not 
    - !Equals 
      - !Ref environment
      - prod
Resources:
  HostedZone:
    Type: AWS::CloudFormation::Stack
    Condition: isNonProd
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/commons/modules/route53.yml
      Parameters: 
        hostedZoneName: !Sub '${environment}.${parentHostedZoneName}'
        parentHostedZoneId: !Ref parentHostedZoneId

  Certificate:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/commons/modules/acm.yml
      Parameters: 
        hostedZoneName: !If [isNonProd, !Sub '${environment}.${parentHostedZoneName}', !Ref parentHostedZoneName]
        hostedZoneId: !If [isNonProd, !GetAtt HostedZone.Outputs.hostedZoneId, !Ref parentHostedZoneId]

  GitConnection:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/commons/modules/codestar.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment

Outputs:
  certificateARN:
    Value: !GetAtt Certificate.Outputs.certificateARN
    Export:
      Name: !Sub "${project}-${environment}-commons-certificateARN"
  hostedZoneId:
    Value: !If [isNonProd, !GetAtt HostedZone.Outputs.hostedZoneId, !Ref parentHostedZoneId]
    Export:
      Name: !Sub "${project}-${environment}-commons-hostedZoneId"
  hostedZoneName:
    Value: !If [isNonProd, !Sub '${environment}.${parentHostedZoneName}', !Ref parentHostedZoneName]
    Export:
      Name: !Sub "${project}-${environment}-commons-hostedZoneName"