Parameters:
  project:
    Type: String
    Description: Project's name
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${project}-${environment}-frontend-${AWS::Region}
Outputs:
  bucketName:
    Value: !Ref S3Bucket
  bucketDomainName:
    Value: !GetAtt S3Bucket.DomainName