AWSTemplateFormatVersion: 2010-09-09
Parameters:
  project:
    Type: String
    Description: Project's name
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
Resources:
  GitConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Sub ${project}-${environment}-git-connection
      ProviderType: GitHub
      