AWSTemplateFormatVersion: 2010-09-09
Description: Create base networking
Parameters:
  project:
    Type: String
    Description: Alphanumeric and underscore
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  environment:
    Description: Deployment environment
    Type: String
    AllowedValues:
      - dev
      - qa
      - prod
    Default: dev
  vpcNetworkAddress:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.0.0/18
  availabilityZone1:
    Type: "AWS::EC2::AvailabilityZone::Name"
    Description: Availability zone
  availabilityZone2:
    Type: "AWS::EC2::AvailabilityZone::Name"
    Description: Availability zone
  publicSubnet01Address:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.0.0/22
  publicSubnet02Address:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.4.0/22
  privateSubnet01Address:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.8.0/21
  privateSubnet02Address:
    Type: String
    Description: CIDR block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 172.16.16.0/21
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - project
          - environment
      - Label:
          default: Network Configuration
        Parameters:
          - vpcNetworkAddress
          - availabilityZone1
          - availabilityZone2
          - publicSubnet01Address
          - publicSubnet02Address
          - privateSubnet01Address
          - privateSubnet02Address
    ParameterLabels:
      project:
        default: "Project name:"
      environment:
        default: "Deployment environment:"
      vpcNetworkAddress:
        default: "VPC network address (CIDR Block):"
      availabilityZone1:
        default: "First availability zone:"
      availabilityZone2:
        default: "Second availability zone:"
      publicSubnet01Address:
        default: "Public subnet address for first AZ:"
      publicSubnet02Address:
        default: "Public subnet address for second AZ:"
      privateSubnet01Address:
        default: "Private subnet address on first AZ:"
      privateSubnet02Address:
        default: "Private subnet address on second AZ:"
Rules:
  DifferentAZs:
    Assertions:
      - Assert: !Not 
          - !Equals 
            - !Ref availabilityZone1
            - !Ref availabilityZone2
        AssertDescription: The Availability Zones must be different
Conditions:
  isProd: !Equals 
    - !Ref environment
    - prod
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref vpcNetworkAddress
      EnableDnsHostnames: True
      Tags:
        - Key: Name
          Value: !Sub "vpc-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "igw-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  AttachIGW:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicSubnet01:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref publicSubnet01Address
      AvailabilityZone: !Ref availabilityZone1
      Tags:
        - Key: Name
          Value: !Sub "pubsnet01-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  PublicSubnet02:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref publicSubnet02Address
      AvailabilityZone: !Ref availabilityZone2
      Tags:
        - Key: Name
          Value: !Sub "pubsnet02-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  PrivateSubnet01:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref privateSubnet01Address
      AvailabilityZone: !Ref availabilityZone1
      Tags:
        - Key: Name
          Value: !Sub "privsnet01-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  PrivateSubnet02:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref privateSubnet02Address
      AvailabilityZone: !Ref availabilityZone2
      Tags:
        - Key: Name
          Value: !Sub "privsnet02-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  EIP01:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "eip01-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  NatGateway01:
    DependsOn: AttachIGW
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt 
        - EIP01
        - AllocationId
      SubnetId: !Ref PublicSubnet01
      Tags:
        - Key: Name
          Value: !Sub "natgw01-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  EIP02:
    Type: "AWS::EC2::EIP"
    Condition: isProd
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "eip02-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  NatGateway02:
    DependsOn: AttachIGW
    Type: "AWS::EC2::NatGateway"
    Condition: isProd
    Properties:
      AllocationId: !GetAtt 
        - EIP02
        - AllocationId
      SubnetId: !Ref PublicSubnet02
      Tags:
        - Key: Name
          Value: !Sub "natgw02-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "pubrt-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  PublicRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnet01RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet01
      RouteTableId: !Ref PublicRouteTable
  PublicSubnet02RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet02
      RouteTableId: !Ref PublicRouteTable
  PrivateRouteTable01:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "privrt01-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  PrivateRouteTable02:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "privrt01-${project}-${environment}"
        - Key: Environment
          Value: !Ref environment
  NatGateway01Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PrivateRouteTable01
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway01
  NatGateway02Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PrivateRouteTable02
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !If [isProd, !Ref NatGateway02, !Ref NatGateway01]
  PrivateSubnet01RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet01
      RouteTableId: !Ref PrivateRouteTable01
  PrivateSubnet02RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet02
      RouteTableId: !Ref PrivateRouteTable02
Outputs:
  vpcId:
    Description: VPC Id
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-vpcId"
  az01:
    Description: Availability Zone 1
    Value: !GetAtt 
      - PublicSubnet01
      - AvailabilityZone
    Export:
      Name: !Sub "${AWS::StackName}-az01"
  az02:
    Description: Availability Zone 2
    Value: !GetAtt 
      - PublicSubnet02
      - AvailabilityZone
    Export:
      Name: !Sub "${AWS::StackName}-az02"
  azList:
    Description: AZ Comma Separated List
    Value: 
      !Join
        - ','
        - - !GetAtt PublicSubnet01.AvailabilityZone
          - !GetAtt PublicSubnet02.AvailabilityZone
    Export:
      Name: !Sub "${AWS::StackName}-azList"
  publicSubnet01Id:
    Description: Public subnet 1
    Value: !Ref PublicSubnet01
    Export:
      Name: !Sub "${AWS::StackName}-publicSubnet01Id"
  publicSubnet02Id:
    Description: Public subnet 2
    Value: !Ref PublicSubnet02
    Export:
      Name: !Sub "${AWS::StackName}-publicSubnet02Id"
  publicSubnetsIdList:
    Description: Public subnet Ids Comma Separated List
    Value: 
      !Join
        - ','
        - - !Ref PublicSubnet01
          - !Ref PublicSubnet02
    Export:
      Name: !Sub "${AWS::StackName}-publicSubnetsIdList"
  privateSubnet01Id:
    Description: Private app subnet 1
    Value: !Ref PrivateSubnet01
    Export:
      Name: !Sub "${AWS::StackName}-privateSubnet01Id"
  privateSubnet02Id:
    Description: Private app subnet 2
    Value: !Ref PrivateSubnet02
    Export:
      Name: !Sub "${AWS::StackName}-privateSubnet02Id"
  privateSubnetsIdList:
    Description: Private subnet Ids Comma Separated List
    Value: 
      !Join
        - ','
        - - !Ref PrivateSubnet01
          - !Ref PrivateSubnet02
    Export:
      Name: !Sub "${AWS::StackName}-privateSubnetsIdList"
