Parameters:
  project:
    Type: String
  environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  service:
    Type: String
Resources:
  ImageRepository:
    Type: AWS::ECR::Repository
    Properties: 
      EncryptionConfiguration: 
        EncryptionType: KMS
      ImageScanningConfiguration: 
        ScanOnPush: True
      ImageTagMutability: MUTABLE
      RepositoryName: !Sub 'ecr-${project}-${environment}-${service}'

Outputs:
  imageRepositoryName:
    Description: Image Repository Name
    Value: !Ref ImageRepository
    Export:
      Name: !Sub '${AWS::StackName}-imageRepositoryName'
  imageRepositoryURI:
    Description: Image Repository URI
    Value: !GetAtt ImageRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-imageRepositoryURI'
  imageRepositoryARN:
    Description: Image Repository ARN
    Value: !GetAtt ImageRepository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-imageRepositoryARN'