AWSTemplateFormatVersion: 2010-09-09 
Description: Deploy a ECS + Fargate common resources.
Parameters:
  project:
    Type: String
  environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  cfnBucketName:
    Type: String
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - project
          - environment
      - Label:
          default: Other information
        Parameters:
          - cfnBucketName
    ParameterLabels:
      project:
        default: "Project's name:"
      environment:
        default: "Project's environment:"
      cfnBucketName:
        default: "Cloudformation bucket:"
Conditions:
  isProd: !Equals 
    - !Ref environment
    - prod
Resources:
  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/backend/cluster/modules/ecs-cluster.yml
      Parameters: 
        environment: !Ref environment
        project: !Ref project
        vpcId: 
          Fn::ImportValue:
            !Sub ${project}-${environment}-shared-vpcId

  DNSNamespace:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/backend/cluster/modules/dns-namespace.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        namespace: !If [isProd, !Sub "${project}.io", !Sub "${environment}.${project}.io"]
        vpcId:
          Fn::ImportValue:
            !Sub ${project}-${environment}-shared-vpcId

  DockerHubSecret:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/backend/cluster/modules/secrets-manager.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        name: dockerhub
        secretTemplate: |
          {
            "DOCKER_HUB_USER": "",
            "DOCKER_HUB_TOKEN": ""
          }

Outputs:
  clusterName:
    Description: Cluster Name
    Value: !GetAtt ECSCluster.Outputs.clusterName
    Export:
      Name: !Sub '${project}-${environment}-cluster-clusterName'
  clusterARN:
    Description: Cluster ARN
    Value: !GetAtt ECSCluster.Outputs.clusterARN
    Export:
      Name: !Sub '${project}-${environment}-cluster-clusterARN'
  autoScalingRoleName:
    Description: Auto Scaling Role Name
    Value: !GetAtt ECSCluster.Outputs.autoScalingRoleName
    Export:
      Name: !Sub '${project}-${environment}-cluster-autoScalingRoleName'
  autoScalingRoleARN:
    Description: Auto Scaling Role ARN
    Value: !GetAtt ECSCluster.Outputs.autoScalingRoleARN
    Export:
      Name: !Sub '${project}-${environment}-cluster-autoScalingRoleARN'
  executionRoleARN:
    Description: Execution Role ARN
    Value: !GetAtt ECSCluster.Outputs.executionRoleARN
    Export:
      Name: !Sub '${project}-${environment}-cluster-executionRoleARN'
  containerInternalSecurityGroupId:
    Description: Container Internal Security Group Id
    Value: !GetAtt ECSCluster.Outputs.containerInternalSecurityGroupId
    Export:
      Name: !Sub '${project}-${environment}-cluster-containerInternalSecurityGroupId'
  namespaceId:
    Description: Namespace Id
    Value: !GetAtt DNSNamespace.Outputs.namespaceId
    Export:
      Name: !Sub '${project}-${environment}-cluster-namespaceId'
  dockerHubSecretARN:
    Description: Secret ARN
    Value: !GetAtt DockerHubSecret.Outputs.secretARN
    Export:
      Name: !Sub "${project}-${environment}-cluster-dockerHubSecretARN"
  dockerHubSecretName:
    Description: Secret Name
    Value: !GetAtt DockerHubSecret.Outputs.secretName
    Export:
      Name: !Sub "${project}-${environment}-cluster-dockerHubSecretName"