AWSTemplateFormatVersion: 2010-09-09
Parameters:
  project:
    Type: String
    Description: Alphanumeric and underscore
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  cfnBucketName:
    Type: String
    Description: Bucket that store cfn modules
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Project Information
        Parameters:
          - project
          - cfnBucketName
    ParameterLabels:
      project:
        default: "Project's name:"
      cfnBucketName:
        default: "Cloudformation bucket:"
Resources:
  GitConnection:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/base/modules/codestar.yml
      Parameters: 
        project: !Ref project

  PipelineBucket:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/base/modules/s3.yml
      Parameters: 
        bucketName: !Sub ${project}-pipeline-artifacts-${AWS::Region}

Outputs:
  gitConnectionARN:
    Value: !GetAtt GitConnection.Outputs.gitConnectionARN
    Export:
      Name: !Sub "${project}-base-gitConnectionARN"
  pipelineBucketName:
    Value: !GetAtt PipelineBucket.Outputs.bucketName
    Export:
      Name: !Sub "${project}-base-pipelineBucketName"
  pipelineBucketDomainName:
    Value: !GetAtt PipelineBucket.Outputs.bucketDomainName
    Export:
      Name: !Sub "${project}-base-pipelineBucketDomainName"