AWSTemplateFormatVersion: "2010-09-09"
Description: Codebuild Project

Parameters:
  project:
    Type: String
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  codeBuildRoleArn:
    Type: String
  buildFolder:
    Type: String
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: !Sub ${project}-${environment}-build
      Description: Build project
      Artifacts: 
        Type: CODEPIPELINE
      BadgeEnabled: False
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Type: PLAINTEXT
            Value: ""
          - Name: BUILD_FOLDER
            Type: PLAINTEXT
            Value: !Ref buildFolder
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: True
        Type: LINUX_CONTAINER
      QueuedTimeoutInMinutes: 60
      ServiceRole: !Ref codeBuildRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          env:
            shell: /bin/sh
            variables:
              PROFILE_NAME: "builder"
          phases:
            install:
              runtime-versions:
                nodejs: latest
              commands:
                - npm -v
                - node -v
                # Install node dependencies
                - npm install
            build:
              commands:
                # Build project
                - npm run build
            post_build:
              commands:
                # Prepare artifacts
                - OUTPUT_FOLDER=$BUILD_FOLDER
                # - OUTPUT_FOLDER=v.${CODEBUILD_BUILD_NUMBER}
                # - mkdir $OUTPUT_FOLDER
                # - cp -rp BUILD_FOLDER/* $OUTPUT_FOLDER/
          artifacts:
            files:
              - $OUTPUT_FOLDER/**/*
            name: BUILD
      TimeoutInMinutes: 60
      Visibility: PRIVATE

Outputs:
  codeBuildProjectName:
    Value: !Ref CodeBuildProject
  codeBuildProjectArn:
    Value: !GetAtt CodeBuildProject.Arn