Parameters:
  project:
    Type: String
    Description: Project's name
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  cfnBucketName:
    Type: String
    Description: Bucket that store cfn modules
  frontendRepository:
    Type: String
Resources:
  Permissions:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/pipeline/iam.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        artifactsBucketName: 
          Fn::ImportValue:
            !Sub "${project}-${environment}-commons-pipelineBucketName"
  BuildProject:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/pipeline/codebuild.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        codeBuildRoleArn: !GetAtt Permissions.Outputs.buildRoleArn
  PipelineProject:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/pipeline/codepipeline.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        artifactsBucketName: 
          Fn::ImportValue:
            !Sub "${project}-${environment}-commons-pipelineBucketName"
        repositoryName: !Ref frontendRepository
        codePipelineRoleArn: !GetAtt Permissions.Outputs.pipelineRoleArn
        gitConnectionArn: 
          Fn::ImportValue:
            !Sub "${project}-${environment}-commons-gitConnectionARN"
        buildProjectName: !GetAtt BuildProject.Outputs.codeBuildProjectName