AWSTemplateFormatVersion: 2010-09-09 
Description: Create IAM Permissions for ECS TaskDefinitions.
Parameters:
  project:
    Type: String
  environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
Resources:
  # A role for the containers
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'iam-${project}-${environment}-task-role'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      # Policies:
      #   -
      Tags:
        - Key: Name
          Value: !Sub 'iam-${project}-${environment}-task-role'

Outputs:
  taskRoleARN:
    Description: Task Role ARN
    Value: !GetAtt TaskRole.Arn